source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"

gem "minima"

group :jekyll_plugins do
  gem "jekyll-airtable-import", path: "../"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "webrick", "~> 1.8"
